// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// correlation_event
NumericVector correlation_event(NumericVector x, NumericVector y);
RcppExport SEXP _eseis_correlation_event(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(correlation_event(x, y));
    return rcpp_result_gen;
END_RCPP
}
// kurtosis_event
NumericVector kurtosis_event(NumericVector x, int k);
RcppExport SEXP _eseis_kurtosis_event(SEXP xSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(kurtosis_event(x, k));
    return rcpp_result_gen;
END_RCPP
}
// run_cor
NumericVector run_cor(NumericVector x, NumericVector y, int k);
RcppExport SEXP _eseis_run_cor(SEXP xSEXP, SEXP ySEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(run_cor(x, y, k));
    return rcpp_result_gen;
END_RCPP
}
// stalta_event_freeze
NumericVector stalta_event_freeze(int event_length, NumericVector data_sta, NumericVector data_lta, double on, double off);
RcppExport SEXP _eseis_stalta_event_freeze(SEXP event_lengthSEXP, SEXP data_staSEXP, SEXP data_ltaSEXP, SEXP onSEXP, SEXP offSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type event_length(event_lengthSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type data_sta(data_staSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type data_lta(data_ltaSEXP);
    Rcpp::traits::input_parameter< double >::type on(onSEXP);
    Rcpp::traits::input_parameter< double >::type off(offSEXP);
    rcpp_result_gen = Rcpp::wrap(stalta_event_freeze(event_length, data_sta, data_lta, on, off));
    return rcpp_result_gen;
END_RCPP
}
// stalta_event_nofreeze
NumericVector stalta_event_nofreeze(int event_length, NumericVector ratio, double on, double off);
RcppExport SEXP _eseis_stalta_event_nofreeze(SEXP event_lengthSEXP, SEXP ratioSEXP, SEXP onSEXP, SEXP offSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type event_length(event_lengthSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ratio(ratioSEXP);
    Rcpp::traits::input_parameter< double >::type on(onSEXP);
    Rcpp::traits::input_parameter< double >::type off(offSEXP);
    rcpp_result_gen = Rcpp::wrap(stalta_event_nofreeze(event_length, ratio, on, off));
    return rcpp_result_gen;
END_RCPP
}
